"""Fix relationships and primary keys

Revision ID: 7f0c9ada9f54
Revises: 419cf71e3914
Create Date: 2025-01-18 02:46:27.990240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0c9ada9f54'
down_revision: Union[str, None] = '419cf71e3914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
